# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af2e95dfbdcccb8fe3410ef69a1acc52111c6cd4bccf98e27c74412bd0319cfdd1bc862c8cec01abb1190ad6e0ad14f9a78e525d9f286112c4915487e25a3fa1

test:
  secret_key_base: c46a52ae98fe9742f60019adebd881061cfb4769d9ce9fbc58757013cb5afeb0db4974dc1ea4d817ce644ff897418efd31655ebcadff3c3d9b498f5c202a79b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
